/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteSuaHistoriaRouteImport } from './routes/conte-sua-historia'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminQuadrosRouteImport } from './routes/admin.quadros'
import { Route as AdminNovaSenhaRouteImport } from './routes/admin_.nova-senha'
import { Route as AdminRecuperarSenhaRouteImport } from './routes/admin_.recuperar-senha'
import { Route as EpisodiosIndexRouteImport } from './routes/episodios.index'
import { Route as EpisodiosSlugRouteImport } from './routes/episodios.$slug'
import { Route as QuadrosIndexRouteImport } from './routes/quadros.index'
import { Route as QuadrosTurbulenciaRouteImport } from './routes/quadros.turbulencia'
import { Route as QuadrosVidaABordoRouteImport } from './routes/quadros.vida-a-bordo'
import { Route as AdminEpisodiosIndexRouteImport } from './routes/admin.episodios.index'
import { Route as AdminEpisodiosEditarRouteImport } from './routes/admin.episodios.editar'
import { Route as AdminEpisodiosNovoRouteImport } from './routes/admin.episodios.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteSuaHistoriaRoute = ConteSuaHistoriaRouteImport.update({
  id: '/conte-sua-historia',
  path: '/conte-sua-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuadrosRoute = AdminQuadrosRouteImport.update({
  id: '/quadros',
  path: '/quadros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNovaSenhaRoute = AdminNovaSenhaRouteImport.update({
  id: '/admin_/nova-senha',
  path: '/admin/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecuperarSenhaRoute = AdminRecuperarSenhaRouteImport.update({
  id: '/admin_/recuperar-senha',
  path: '/admin/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosIndexRoute = EpisodiosIndexRouteImport.update({
  id: '/episodios/',
  path: '/episodios/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodiosSlugRoute = EpisodiosSlugRouteImport.update({
  id: '/episodios/$slug',
  path: '/episodios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrosIndexRoute = QuadrosIndexRouteImport.update({
  id: '/quadros/',
  path: '/quadros/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrosTurbulenciaRoute = QuadrosTurbulenciaRouteImport.update({
  id: '/quadros/turbulencia',
  path: '/quadros/turbulencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrosVidaABordoRoute = QuadrosVidaABordoRouteImport.update({
  id: '/quadros/vida-a-bordo',
  path: '/quadros/vida-a-bordo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEpisodiosIndexRoute = AdminEpisodiosIndexRouteImport.update({
  id: '/episodios/',
  path: '/episodios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodiosEditarRoute = AdminEpisodiosEditarRouteImport.update({
  id: '/episodios/editar',
  path: '/episodios/editar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEpisodiosNovoRoute = AdminEpisodiosNovoRouteImport.update({
  id: '/episodios/novo',
  path: '/episodios/novo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conte-sua-historia': typeof ConteSuaHistoriaRoute
  '/historias': typeof HistoriasRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/quadros': typeof AdminQuadrosRoute
  '/admin/nova-senha': typeof AdminNovaSenhaRoute
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/quadros/turbulencia': typeof QuadrosTurbulenciaRoute
  '/quadros/vida-a-bordo': typeof QuadrosVidaABordoRoute
  '/admin/': typeof AdminIndexRoute
  '/episodios/': typeof EpisodiosIndexRoute
  '/quadros/': typeof QuadrosIndexRoute
  '/admin/episodios/editar': typeof AdminEpisodiosEditarRoute
  '/admin/episodios/novo': typeof AdminEpisodiosNovoRoute
  '/admin/episodios/': typeof AdminEpisodiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/conte-sua-historia': typeof ConteSuaHistoriaRoute
  '/historias': typeof HistoriasRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/quadros': typeof AdminQuadrosRoute
  '/admin/nova-senha': typeof AdminNovaSenhaRoute
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/quadros/turbulencia': typeof QuadrosTurbulenciaRoute
  '/quadros/vida-a-bordo': typeof QuadrosVidaABordoRoute
  '/admin': typeof AdminIndexRoute
  '/episodios': typeof EpisodiosIndexRoute
  '/quadros': typeof QuadrosIndexRoute
  '/admin/episodios/editar': typeof AdminEpisodiosEditarRoute
  '/admin/episodios/novo': typeof AdminEpisodiosNovoRoute
  '/admin/episodios': typeof AdminEpisodiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/conte-sua-historia': typeof ConteSuaHistoriaRoute
  '/historias': typeof HistoriasRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/quadros': typeof AdminQuadrosRoute
  '/admin_/nova-senha': typeof AdminNovaSenhaRoute
  '/admin_/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/episodios/$slug': typeof EpisodiosSlugRoute
  '/quadros/turbulencia': typeof QuadrosTurbulenciaRoute
  '/quadros/vida-a-bordo': typeof QuadrosVidaABordoRoute
  '/admin/': typeof AdminIndexRoute
  '/episodios/': typeof EpisodiosIndexRoute
  '/quadros/': typeof QuadrosIndexRoute
  '/admin/episodios/editar': typeof AdminEpisodiosEditarRoute
  '/admin/episodios/novo': typeof AdminEpisodiosNovoRoute
  '/admin/episodios/': typeof AdminEpisodiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/conte-sua-historia'
    | '/historias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/links'
    | '/admin/perfil'
    | '/admin/quadros'
    | '/admin/nova-senha'
    | '/admin/recuperar-senha'
    | '/episodios/$slug'
    | '/quadros/turbulencia'
    | '/quadros/vida-a-bordo'
    | '/admin/'
    | '/episodios/'
    | '/quadros/'
    | '/admin/episodios/editar'
    | '/admin/episodios/novo'
    | '/admin/episodios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/conte-sua-historia'
    | '/historias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/links'
    | '/admin/perfil'
    | '/admin/quadros'
    | '/admin/nova-senha'
    | '/admin/recuperar-senha'
    | '/episodios/$slug'
    | '/quadros/turbulencia'
    | '/quadros/vida-a-bordo'
    | '/admin'
    | '/episodios'
    | '/quadros'
    | '/admin/episodios/editar'
    | '/admin/episodios/novo'
    | '/admin/episodios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/conte-sua-historia'
    | '/historias'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/links'
    | '/admin/perfil'
    | '/admin/quadros'
    | '/admin_/nova-senha'
    | '/admin_/recuperar-senha'
    | '/episodios/$slug'
    | '/quadros/turbulencia'
    | '/quadros/vida-a-bordo'
    | '/admin/'
    | '/episodios/'
    | '/quadros/'
    | '/admin/episodios/editar'
    | '/admin/episodios/novo'
    | '/admin/episodios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ConteSuaHistoriaRoute: typeof ConteSuaHistoriaRoute
  HistoriasRoute: typeof HistoriasRoute
  SobreRoute: typeof SobreRoute
  AdminNovaSenhaRoute: typeof AdminNovaSenhaRoute
  AdminRecuperarSenhaRoute: typeof AdminRecuperarSenhaRoute
  EpisodiosSlugRoute: typeof EpisodiosSlugRoute
  QuadrosTurbulenciaRoute: typeof QuadrosTurbulenciaRoute
  QuadrosVidaABordoRoute: typeof QuadrosVidaABordoRoute
  EpisodiosIndexRoute: typeof EpisodiosIndexRoute
  QuadrosIndexRoute: typeof QuadrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conte-sua-historia': {
      id: '/conte-sua-historia'
      path: '/conte-sua-historia'
      fullPath: '/conte-sua-historia'
      preLoaderRoute: typeof ConteSuaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quadros': {
      id: '/admin/quadros'
      path: '/quadros'
      fullPath: '/admin/quadros'
      preLoaderRoute: typeof AdminQuadrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/nova-senha': {
      id: '/admin_/nova-senha'
      path: '/admin/nova-senha'
      fullPath: '/admin/nova-senha'
      preLoaderRoute: typeof AdminNovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/recuperar-senha': {
      id: '/admin_/recuperar-senha'
      path: '/admin/recuperar-senha'
      fullPath: '/admin/recuperar-senha'
      preLoaderRoute: typeof AdminRecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios/': {
      id: '/episodios/'
      path: '/episodios'
      fullPath: '/episodios/'
      preLoaderRoute: typeof EpisodiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodios/$slug': {
      id: '/episodios/$slug'
      path: '/episodios/$slug'
      fullPath: '/episodios/$slug'
      preLoaderRoute: typeof EpisodiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadros/': {
      id: '/quadros/'
      path: '/quadros'
      fullPath: '/quadros/'
      preLoaderRoute: typeof QuadrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadros/turbulencia': {
      id: '/quadros/turbulencia'
      path: '/quadros/turbulencia'
      fullPath: '/quadros/turbulencia'
      preLoaderRoute: typeof QuadrosTurbulenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadros/vida-a-bordo': {
      id: '/quadros/vida-a-bordo'
      path: '/quadros/vida-a-bordo'
      fullPath: '/quadros/vida-a-bordo'
      preLoaderRoute: typeof QuadrosVidaABordoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/episodios/': {
      id: '/admin/episodios/'
      path: '/episodios'
      fullPath: '/admin/episodios/'
      preLoaderRoute: typeof AdminEpisodiosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodios/editar': {
      id: '/admin/episodios/editar'
      path: '/episodios/editar'
      fullPath: '/admin/episodios/editar'
      preLoaderRoute: typeof AdminEpisodiosEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/episodios/novo': {
      id: '/admin/episodios/novo'
      path: '/episodios/novo'
      fullPath: '/admin/episodios/novo'
      preLoaderRoute: typeof AdminEpisodiosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminQuadrosRoute: typeof AdminQuadrosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEpisodiosEditarRoute: typeof AdminEpisodiosEditarRoute
  AdminEpisodiosNovoRoute: typeof AdminEpisodiosNovoRoute
  AdminEpisodiosIndexRoute: typeof AdminEpisodiosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminQuadrosRoute: AdminQuadrosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEpisodiosEditarRoute: AdminEpisodiosEditarRoute,
  AdminEpisodiosNovoRoute: AdminEpisodiosNovoRoute,
  AdminEpisodiosIndexRoute: AdminEpisodiosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ConteSuaHistoriaRoute: ConteSuaHistoriaRoute,
  HistoriasRoute: HistoriasRoute,
  SobreRoute: SobreRoute,
  AdminNovaSenhaRoute: AdminNovaSenhaRoute,
  AdminRecuperarSenhaRoute: AdminRecuperarSenhaRoute,
  EpisodiosSlugRoute: EpisodiosSlugRoute,
  QuadrosTurbulenciaRoute: QuadrosTurbulenciaRoute,
  QuadrosVidaABordoRoute: QuadrosVidaABordoRoute,
  EpisodiosIndexRoute: EpisodiosIndexRoute,
  QuadrosIndexRoute: QuadrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
